Possibility to use custom allocators for nodes retrieved from cursors and queries
tree-sitter/java-tree-sitter pull request #63
Opened 2024-12-11 13:35 UTC by Emmeral

Fixes #57 

Allows to use a custom `SegmentAllocator` when retrieving node instances from cursors and queries. This allows for using the nodes even after the cursor / query has been closed. Also it gives the caller the opportunity to clear the memory of a node without closing the cursor / query in case a lot of nodes are retrieved without closing the cursor / query.

Note: This PR also removes the cached java node object in the `TreeCursor` class as we do now longer control the lifetime of its native memory. I hope this is ok as recreating it (in case somebody retrieves the same node twice) should not be that expensive.

2024-12-11 14:49 UTC, ObserverOfTime requested changes

2024-12-11 14:49 UTC, ObserverOfTime commented on src/main/java/io/github/treesitter/jtreesitter/TreeCursor.java
Keep the node caching as it was.

2024-12-11 14:49 UTC, ObserverOfTime commented on src/test/java/io/github/treesitter/jtreesitter/TreeCursorTest.java
> +            cursor = null; // avoid double close
Clone the cursor and close the copy instead.

2024-12-11 14:49 UTC, ObserverOfTime commented on src/main/java/io/github/treesitter/jtreesitter/Query.java
Move the memory management parts of the docs to `@implNote`s.

2024-12-11 14:50 UTC, ObserverOfTime commented on src/main/java/io/github/treesitter/jtreesitter/Query.java
Actually, I'll clean up the docs later anyway.

2024-12-13 10:11 UTC, Emmeral commented
I implemented the requested changes. Could you please re-review @ObserverOfTime ?

2025-01-01 15:52 UTC, ObserverOfTime commented on src/main/java/io/github/treesitter/jtreesitter/Query.java
> +    public Stream<QueryMatch> findMatches(Node node, @Nullable BiPredicate<QueryPredicate, QueryMatch> predicate, SegmentAllocator allocator) {
[Kotlin convention](https://kotlinlang.org/docs/lambdas.html#passing-trailing-lambdas)
```suggestion
    public Stream<QueryMatch> findMatches(Node node, SegmentAllocator allocator, @Nullable BiPredicate<QueryPredicate, QueryMatch> predicate) {
```

2025-01-02 07:26 UTC, Emmeral commented on src/main/java/io/github/treesitter/jtreesitter/Query.java
> +    public Stream<QueryMatch> findMatches(Node node, @Nullable BiPredicate<QueryPredicate, QueryMatch> predicate, SegmentAllocator allocator) {
Changed

2025-02-06 07:47 UTC, merged